### ISSUE TITLE
Add Error Handling for Data Load Failures in Loader Class

### ISSUE THREAD

**Issue by kavs2803** [acmpesuecc/ModelForge#1]
The current implementation of the Loader class assumes that the dataset will always load successfully. However, if the dataset file is missing, corrupt, or in an unsupported format, the class does not handle these scenarios, leading to crashes or undefined behavior.

**Comment by Asymtode712** [comment]
@kavs2803 I would like to work on this issue if it is up for grabs.....

**Comment by avinash-selvan** [comment]
Can I be assigned to this issue?

**Comment by Spinicle** [comment]
Can I be assigned to this issue?
My internet lil slow so it was sent late😭

**Comment by Viprakshi** [comment]
assign me this @yashmithaa

**Comment by kavs2803** [comment]
!assign @avinaldo22

**Comment by kavs2803** [comment]
!assign @Spinicle

**Comment by kavs2803** [comment]
!assign @Viprakshi

**Comment by Spinicle** [comment]
Wait why did I not get assigned?

**Comment by yashmithaa** [comment]
@Spinicle have you been assigned some other issue? if you want to work on this issue, please deassign from your previous issue

**Comment by Spinicle** [comment]
I did un assign myself, didn't ask to be de-assigned though

**Comment by yashmithaa** [comment]
!assign @Spinicle

**Comment by RithishRM** [comment]
I want this issue

**Comment by Spinicle** [comment]
Should I ask to de-assign me?

**Comment by yashmithaa** [comment]
!assign @DedLad

**Comment by yashmithaa** [comment]
!deassign

**Comment by RithishRM** [comment]
Can I get this issue now ??

**Comment by Spinicle** [comment]
Hey~ So I've asked them to de-assign, just waiting on their reply

**Comment by QWERTY-Ak** [comment]
can i get assinged to this

**Comment by Spinicle** [comment]
Could you try assigning now?

**Comment by yashmithaa** [comment]
!assign @avinaldo22 10

**Comment by Spinicle** [comment]
Could you try assigning now? I've been de-assigned

**Comment by Spinicle** [comment]
@yashmithaa

**Comment by satoqibi** [comment]
Hi, Can you assign this to me please

**Comment by mebinthattil** [comment]
Hi, can this issue be assigned to me

**Comment by yashmithaa** [comment]
!assign @satoqibi

**Comment by satoqibi** [comment]
I have sent a pull request, please review it.

**Comment by yashmithaa** [comment]
!deassign
