### ISSUE TITLE
 Improve Logging System

### ISSUE THREAD

**Issue by yashmithaa** [acmpesuecc/ModelForge#3]
The current logging system logs all messages to a single file, which can grow excessively large over time, especially when handling long-running processes or large datasets. This can make it difficult to manage and review logs efficiently. To address this, We need to implement log rotation, which will automatically split the log file once it reaches a certain size, creating a new file while keeping the older logs available.
- The logging system should automatically rotate the log files once they reach a specified size (e.g. 2 MB)
- Older log files should be saved with appropriate timestamps or numbering, allowing easy access to previous logs.
- You can also expand the logging system to include additional levels ( `DEBUG` / `WARNING` / `ERROR` )

**Comment by RithishRM** [comment]
I want this issue

**Comment by yashmithaa** [comment]
!assign @RithishRM

**Comment by mahika34** [comment]
can i be assigned pls?

**Comment by kavs2803** [comment]
!assign @mahika34

**Comment by kavs2803** [comment]
to be assigned to this issue, you should be working only on this issue and must be deassigned from any other issue that you are working on

**Comment by mahika34** [comment]
i want to be deassigned

**Comment by kavs2803** [comment]
!assign @mahika34

**Comment by RithishRM** [comment]
Do I still have this issue assigned

**Comment by kavs2803** [comment]
to be assigned , please be deassigned from any other issue that you are working on

**Comment by Darshanpawar7** [comment]
assign me

**Comment by Darshanpawar7** [comment]
@kavs2803

**Comment by yashmithaa** [comment]
!assign @Darshanpawar7

**Comment by mahika34** [comment]
can i be assigned

**Comment by yashmithaa** [comment]
!assign @mahika34

**Comment by yashmithaa** [comment]
!deassign @Darshanpawar7

**Comment by yashmithaa** [comment]
!assign @mahika34

**Comment by Spinicle** [comment]
Is anyone still assigned? I'd like to be assigned if no one is

**Comment by yashmithaa** [comment]
!assign @Spinicle

**Comment by Spinicle** [comment]
Need an extension, both one and two are interconnected so getting one would mean I would do the second one too

**Comment by yashmithaa** [comment]
!deassign

**Comment by yashmithaa** [comment]
!assign @Spinicle

**Comment by Spinicle** [comment]
@yashmithaa Could you please pop in here for a minute?

**Comment by Spinicle** [comment]
@yashmithaa Could you extend? 🥺(and also pop in for a while, apparently i missed you)

**Comment by Spinicle** [comment]
@yashmithaa I did something and I think it ran, could you come check?

**Comment by yashmithaa** [comment]
!deassign @Spinicle
