### ISSUE TITLE
Implement Progress Bar for Dataset Processing

### ISSUE THREAD

**Issue by kavs2803** [acmpesuecc/ModelForge#4]
Currently, users don’t get feedback on how long the process will take or how much has been completed.
Add a progress bar (using libraries like tqdm) to show progress when loading, cleaning, and splitting the dataset, especially for large datasets.

**Comment by codebuddyjr** [comment]
assign this

**Comment by yashmithaa** [comment]
!assign @codebuddyjr

**Comment by yashmithaa** [comment]
!assign @codebuddyjr

**Comment by mahika34** [comment]
can i be assigned

**Comment by bwaklog** [comment]
!deassign

**Comment by bwaklog** [comment]
@codebuddyjr you are free to work on other issues
